<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1248d66d-fa2c-418e-b8f9-b6ec094aa994</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.3" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.79.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.79.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiEngineeringLab.Core\AiEngineeringLab.Core.csproj" />
	<ProjectReference Include="..\AiEngineeringLab.Plugins\AiEngineeringLab.Plugins.csproj" />
  </ItemGroup>

</Project>
